apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: demoweb
  namespace: flux-system
spec:
  chart: demoweb
  sourceRef:
    name: apps
    kind: GitRepository
  interval: 10m