
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demoweb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: demoweb
      sourceRef:
        kind: GitRepository
        name: apps
        namespace: flux-system
      interval: 1m
  values:
    version: "1"
    info: project1-aks-we
