apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demoweb
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tkubica12/iac-gitops
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/