apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/tkubica12/iac-gitops.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/
  secretRef:
    name: app